## Final Project: Reading the sea-ice parameters
### Importing a .csv file into a dataframe and array 
The imported file is a .csv file obtained from the .nc format. This contains two variables namely, Sea Ice Thickness (SIT) and Zonal Wave 3 Index (ZW3) which have been averaged over the global grids.

In [126]:
import numpy as np
import pandas as pd

path = 'sea_ice_parameters.csv'
df = pd.read_csv(path)
sea_ice=df.to_numpy()

df

     Date    SIT  Zonal_Wave_3
0   10-02  -4985         0.381
1    5-03 -33087         0.262
2    6-03  -9663        -0.788
3    7-03  12339         0.000
4    8-03  16822         0.177
5    9-03  14002        -0.888
6   10-03 -18128        -0.707
7    5-04 -28029         0.273
8    6-04    423         0.518
9    7-04  23952        -0.923
10   8-04  22424        -0.081
11   9-04  13711        -0.344
12  10-04 -20650        -0.189
13   5-05 -38101        -0.927
14   6-05  -3019        -0.548
15   7-05  12548         0.288
16   8-05  16349        -0.018
17   9-05  19395         0.597
18  10-05 -17627         1.080
19   5-06 -46043        -0.087
20   6-06 -19476        -0.377
21   7-06   1689        -0.234
22   8-06  18225         0.950
23   9-06   7940        -0.291
24  10-06 -20025         0.242
25   5-07 -47351         0.013
26   6-07 -16009        -0.394
27   7-07  14371         0.541
28   8-07  18399         0.062
29   9-07  24376         0.556
30  10-07 -18108        -0.514
31   5-08 -33366         0.092
32   6-08  -2720         0.651
33   7-08  18877         0.217
34   8-08  28009        -1.345
35   9-08  31875         0.648
36  10-08 -14588        -0.235
37   5-09 -32704        -0.393
38   6-09  -2096         0.619
39   7-09  19610        -0.010
40   8-09  39734         0.455
41   9-09  38681         0.110
42  10-09 -13439        -1.572
43   5-10 -37565         0.259
44   6-10 -12205        -0.402
45   7-10  16703        -0.161
46   8-10  23323        -0.328
47   9-10  21770        -0.927
48  10-10 -15045         0.106
49   5-11 -41217        -0.823
50   6-11 -12009         0.001
51   7-11  19043        -1.317
52   8-11  30775         0.775
53   9-11  31892        -0.608
54  10-11      0         0.186

In [129]:
print("Dimensions of the csv file: \n\n",sea_ice.shape)

Dimensions of the csv file:

 (55, 3)

In [120]:
print("Average of SIT: \n\n",np.mean(sea_ice[:,1]))


print("\n\n Average of Zonal Wave 3: \n\n",np.mean(sea_ice[:,2]))

Average of SIT:

 0.03636363636363636


 Average of Zonal Wave 3:

 -0.09767272727272726

### Average:
The mean values give an idea of the central mass of the variable.

### Standard Deviation 
The SD values give an idea about the variabilities in the parameter. In this case, a very high value of Sea ice Thickness (SIT) means that the value differs a lot from its mean value wiht a very high variability observed over the given time period.

In [124]:
print("Standard Deviation of SIT: \n\n",np.std(sea_ice[:,1]))

print("\n\n Standard Dev. of Zonal Wave 3: \n\n",np.std(sea_ice[:,2]))

Standard Deviation of SIT:

 23333.009911409852


 Standard Dev. of Zonal Wave 3:

 0.582585617727962

### Sorting the columns to see when the maximum and minimum SIT values were reached within a year as well as during the entire time period.
The sorting gives us the values which we were expecting from the dataset. The start of the winters in southern hemisphere (i.e. May and June) will show the minimum SIT values (anomalies which are described as variaiton from the mean value). The negative anomaly values mean that the thickness is very less as the snow is yet to fall and get accumulated. The maximum or positive SIT anomalies are seen by the end of winters or start of spring (August-September) when the snow season ends and the accumulation is maximum.

In [130]:
df.sort_values(by='SIT')

     Date    SIT  Zonal_Wave_3
25   5-07 -47351         0.013
19   5-06 -46043        -0.087
49   5-11 -41217        -0.823
13   5-05 -38101        -0.927
43   5-10 -37565         0.259
31   5-08 -33366         0.092
1    5-03 -33087         0.262
37   5-09 -32704        -0.393
7    5-04 -28029         0.273
12  10-04 -20650        -0.189
24  10-06 -20025         0.242
20   6-06 -19476        -0.377
6   10-03 -18128        -0.707
30  10-07 -18108        -0.514
18  10-05 -17627         1.080
26   6-07 -16009        -0.394
48  10-10 -15045         0.106
36  10-08 -14588        -0.235
42  10-09 -13439        -1.572
44   6-10 -12205        -0.402
50   6-11 -12009         0.001
2    6-03  -9663        -0.788
0   10-02  -4985         0.381
14   6-05  -3019        -0.548
32   6-08  -2720         0.651
38   6-09  -2096         0.619
54  10-11      0         0.186
8    6-04    423         0.518
21   7-06   1689        -0.234
23   9-06   7940        -0.291
3    7-03  12339         0.000
15   7-05  12548         0.288
11   9-04  13711        -0.344
5    9-03  14002        -0.888
27   7-07  14371         0.541
16   8-05  16349        -0.018
45   7-10  16703        -0.161
4    8-03  16822         0.177
22   8-06  18225         0.950
28   8-07  18399         0.062
33   7-08  18877         0.217
51   7-11  19043        -1.317
17   9-05  19395         0.597
39   7-09  19610        -0.010
47   9-10  21770        -0.927
10   8-04  22424        -0.081
46   8-10  23323        -0.328
9    7-04  23952        -0.923
29   9-07  24376         0.556
34   8-08  28009        -1.345
52   8-11  30775         0.775
35   9-08  31875         0.648
53   9-11  31892        -0.608
41   9-09  38681         0.110
40   8-09  39734         0.455

### Boolean Indexing
#### Selecting data based on the value of a particular column 
This gives us the results similar to the sorting function. But in this case, it helps us to only look at the desired values which are filtered accordingly. 

We notice that its May (05)doesn't have positive anomalies in any of the years while its only in the year 2004 that we see the month of June having a positive SIT anomaly. It can be deduced that the year 2004 experienced an early arrival of winters as well as an early departure since the melting started in October resulting in negative anomalies for that month.

In [137]:
df[df['SIT'] > 0]

    Date    SIT  Zonal_Wave_3
3   7-03  12339         0.000
4   8-03  16822         0.177
5   9-03  14002        -0.888
8   6-04    423         0.518
9   7-04  23952        -0.923
10  8-04  22424        -0.081
11  9-04  13711        -0.344
15  7-05  12548         0.288
16  8-05  16349        -0.018
17  9-05  19395         0.597
21  7-06   1689        -0.234
22  8-06  18225         0.950
23  9-06   7940        -0.291
27  7-07  14371         0.541
28  8-07  18399         0.062
29  9-07  24376         0.556
33  7-08  18877         0.217
34  8-08  28009        -1.345
35  9-08  31875         0.648
39  7-09  19610        -0.010
40  8-09  39734         0.455
41  9-09  38681         0.110
45  7-10  16703        -0.161
46  8-10  23323        -0.328
47  9-10  21770        -0.927
51  7-11  19043        -1.317
52  8-11  30775         0.775
53  9-11  31892        -0.608

### Correlation coefficients 

This statistical operation helps in understanding the relationship between the two variables. In this case, the Sea ice thickness shows about 10% relation with with the Zonal Wave 3.

In [125]:
print("Correlation between SIT and Zonal Wave3: \n\n", df.corr())

Correlation between SIT and Zonal Wave3:

                    SIT  Zonal_Wave_3
SIT           1.000000      0.102306
Zonal_Wave_3  0.102306      1.000000